 var data = [
  {
    "Sottotitolo": "tracce",
    "Titolo": "Testaccio",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Il nome del quartiere Testaccio, uno tra i più iconici e conosciuti di Roma, deriva dal <mi>«Monte dei Cocci»</mi> che lo sovrasta: un muro formato dai resti delle anfore, dei cocci, delle tegole (<mi>testae</mi> in latino) che servivano a trasportare le merci fino alla sponda sinistra del Tevere. Oggi le tegole delle anfore rimangono accatastate nel quartiere, il cui nome deriva dall’espressione latina <mi>Mons Testaceum</mi>. Quello di Testaccio è un caso di toponomastica di diretta derivazione dal Latino, che ci restituisce l'idea di come nel corso del tempo alcuni termini di uso comune in una lingua vengano sostituiti da altri, in base alle preferenze ed esperienze dei parlanti.<br></p>",
    "Descrizione2": "<p style='font-size:18px;'>Il passaggio del tempo cambia la lingua, che subisce modifiche e viene plasmata dai parlanti. Spesso accade che alcuni termini vengano soppiantati da altri: quelli di uso comune sono spesso più soggetti a cambiamenti. Non a caso, la parola TESTA(M), che in latino indica un vaso di terracotta, ha sostituito la parola CAPUT (cranio), la forma usata in latino antico. Oggi, infatti, utilizziamo la parola testa per descrivere la parte del corpo, mentre il termine capo rimane nel nostro patrimonio linguistico, ma è utilizzato molto meno frequentemente in questo senso, se non per descrivere qualcuno che detiene il comando su altre persone (es. capocuoco, capotreno).<br> Si potrebbe pensare che la sostituzione sia dovuta dall’espressione ‘capo vuoto come un vaso’, usata per deridere qualcuno. Con il tempo la venatura ironica scomparve, e il termine CAPUT sopravvisse come capo solo in determinati contesti dotti. Inoltre, nei dialetti del centro Italia (e più specificamente nel Lazio, in Umbria, e in parte delle Marche e dell’Abruzzo), chiamati dialetti mediani, la parola testo si riferisce allo strumento da cucina che si usa per cuocere al forno, mentre la parola coccia indica la buccia della frutta, o a volte anche la testa: tutti questi termini rimandano alla parola latina TESTA(M). La toponomastica di Testaccio non è una traccia materiale o scritta, ma fa comunque parte di un patrimonio condiviso, benché non tutti conoscano la sua origine né sappiano che questo nome è una spia interessante di alcuni meccanismi alla base della lingua italiana e del suo rapporto con il latino.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Luogo:</b> Italia, Roma, Via di Monte Testaccio tra la sponda sinistra del Tevere e le mura Aureliane<br><b>Data:</b> I – III s.<br><b>Lingue:</b> Latino/Italiano/Dialetto Romanesco</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliografia</b><br>Malizia,  Giuliano, <i>Testaccio</i> (Roma: Newton Compton, 1996)<br>Zeppegno, Luciano <i>I rioni di Roma </i>(Roma: Newton Compton, 1996)</p>",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Immagine:</b> I segreti di Roma. it </p>",
    "Autore": "<p align='right'><i>Melissa Alessandrucci</i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/1.png",
    "Type": "true",
    "id": 1
  },
    {
    "Sottotitolo": "tracce",
    "Titolo": "Nonsense words and masturbation in ancient Greece",
     "Image": "Immagini/tracce/traccia_2.png",
    "Descrizione": "<p>An aryballos was a small spherical or globular flask with a narrow neck used in Ancient Greece. It was used to contain perfume or oil, and is often depicted in vase paintings being used by athletes during bathing, being at times attached by a strap to the athlete's wrist, or hung by a strap from a peg on the wall.  Its shape is particularly suited to its function - the athlete could shake the oil out and then apply it to his body with his fingers.<br>Of special interest on this vessel, which is identified as the work of Nearchos by his name being etched on the rear panel of the handle (shown in the illustration),  is the depiction of some words that do not have any specific meaning. All of these scenes include painted inscriptions which are particularly intriguing because they are a mixture of sense, mockery or mimicry, and nonsense.<br></p>",
    "Descrizione2": "<p style='font-size:18px;'>On the rear panel of the handle, along with the graffito of the potter’s signature, are  three squatting, ithyphallic satyrs. These are identified by their written names as Dophios (from dephesthai, to masturbate, “soften”), Terpekelos (‘he who gives pleasure to his shaft’) and Psolas (from psolos, the erect penis with the foreskin retracted) are shown masturbating. The vertical placement of the names of the flanking satyr figures ideographically calls attention to and emphasizes their behavior – and the names are placed alongside meaningless inscriptions. <br>Despite the fact that the majority of the vessels in this period contained letters and inscriptions that gave information about the scenes they depicted, this vessel displays many nonsense words as well as names. A scene of Pygmies fighting cranes dominates the rim, and contains many inscriptions of apparently meaningless words. The frame on the left side of the handle presents a single Perseus figure, facing left, and the frame on the right side of the handle features a single Hermes figure, facing right. Beginning at the end where Hermes stands, the meaningless words on the rim read:  ριο, ουα, σ, κρο, καλ, χος, αρυς, ρορυ, θεν, ακι , θοι, βαυς, πυ.These words are perhaps meant to mimic the cries of the cranes, and maybe even of the depicted pygmies as they battle (Hampe). If we follow Hampe’s suggestion, the nonsense words inscribed on this object, or at least those around the rim, are important because they have an unusual  purpose, providing no narrative but highlighting the sound effects of the battle. As such they contribute to the scene sematographically (related to the use of signs or symbols - especially in relation to Ancient Greek writing), on a visual and an aural level. Other scholars (Immerwalir) claim that they are neither representations of sounds, nor mock inscriptions, nor even representations of name-labels, since the number of such ‘labels’ does not correspond to the number of figures. In this interpretation, the letters here comprise meaningless words, despite the fact that they were painted by a literate painter. The Hermes and Perseus figures also stand among nonsense words or word-fragments, but in their scenes there are also meaningful name-labels.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Location<br>Origins:</b> Greece, Attica, probably in the Acropolis, Athens (Richter 1932). <br><b>Current situation:</b> The Metropolitan Museum of Art, New York<br><b>Dimensions: </b>H. 3 1/16 in. (7.8 cm)<br><b>Materials and Condition:</b> Limestone hermetic column<br><b>Date:</b> ca. 570 B.C.<br><b>Language:</b> Αncient Greek<br><b>Writing system(s) and Script(s):</b> Greek alphabet<br><b>Type of trace:</b> (list one) inscription<br><b>Transcription:</b> Handle plate, front: behind the upper body of the left satyr: χαιρει. In front: Δοφιος{1}. I. e., Δοφιος | χαιρει. Above the head of the middle satyr: Τερπεκηλος{2}. In front of the right satyr, not facing: Φσολας{3}. Behind his upper body: hαοι. To right of his legs: λει and (separated by the tail): βρε. Under the plate, Gr. in the black glaze: Nεαρχος | εποιεσεν με{4}. On the left side of the handle plate, to left of the body: Περσε|ευς, retr. At right: hευ|σετι{5}. On the right side of the handle plate: in the upper left: τει. Between Hermes' legs: hοδι. On his lower right, down: hερμες{6}. On the rim, scattered: ριο, retr. θ[--]. αυασ, retr. κρο. καλ, retr. χοσ. αρυσ. ρορυ. θεν. ακι. ϙε. θοι, retr. βαυσ, retr. πυ. οαι{7}.<br><b>Transliteration:</b> [L. satyr] chairei; [front] Dophios/Thofios; [middle satyr] Terpekelos; [in front of R satyr] Phsolas/Fsolas; [R of R satyr’s legs] lei, bre/vre; [Under the plate] Nearchos | epoiesen me; [L. of handle plate] Perse|ees, retr.; [at R.] hee|seti; [R of handle plate]  tei; [between Hermes’ legs and on his lower R.] hothi,  hermes; [rim, scattered] rio, retr. th[--]. aeas, retr. kro. kal, retr. chos. ares. rore. then. aki. ϙe. thoi, retr. vaes, retr. pe. oai.</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliography</b><br>Bandinelli, Ranuccio Bianchi, Enciclopedia dell'Arte Antica, Classica e Orientale, vol. 5. (Rome: Instituto della Enciclopedia Italiana, 1958), p. 389, fig. 514<br>Beazley, John D., Attic Black-figure Vase-painters (Oxford: Clarendon Press, 1956), pp. 83, 682, no. 4<br>Beazley, John D, Attic Red-figure Vase-painters, 2nd ed. vols. 1, 2 (Oxford: Clarendon Press, 1963[1942]), p. 1607<br>Beazley, John D., Paralipomena: Additions to Attic Black-Figure Vase-Painters and to Attic Red-Figure Vase-Painters (Oxford: Clarendon Press, 1971), p. 30<br>Beazley, John D., The Development of Attic Black Figure, Vol. 24 (Berkeley: University of California Press, 1986), p. 99 [p. 38 n. 11], pl. 32, 5–6 <br>Brijder, Herman A. G., Siana Cups II: The Heidelberg Painter, Allard Pierson Series: Studies in Ancient Civilization, Vol. 8. (Amsterdam: Allard Pierson Museum, 1991), fig. 120<br>Chiarini, Sara, The So-called Nonsense Inscriptions on Ancient Greek Vases: Between Paideia and Paidiá  (Leiden/ Boston: Brill, 2018), pp. 416–17<br>Cohen, Beth, ‘The Literate Potter: A Tradition of Incised Signatures on Attic Vases’, Metropolitan Museum Journal, 26 (1991), pp. 53, 85, figs. 4–5<br>Hedreen, Guy Michael, ‘Involved Spectatorship in Archaic Greek Art’, Art History, 30 (2007), pp. 238, fig. 4.17.<br>Hedreen, Guy Michael, The Image of the Artist in Archaic and Classical Greece: Art, Poetry, and Subjectivity (New York: Cambridge University Press, 2016), pp. 205–7, fig. 34 <br>Hedreen, Guy Michael, ‘The Frontal Face in Athenian Vase-Painting’, in The Frame in Classical Art : A Cultural History, ed. by Verity Platt and Michael Squire (Cambridge: Cambridge University Press), pp. 174–75, fig. 3.10<br>Heesen, Pieter, Athenian little-master cups (Amsterdam: Pieter Heesen, 2017), nn. 77, 1230<br>‘Dophios’, in Lexicon Iconographicum Mythologiae Classicae (LIMC), vol. 3: Atherion-Eros (Zürich: Artemis Verlag, 1986), p. 666, no. 1 <br>‘Hermes’, in Lexicon Iconographicum Mythologiae Classicae (LIMC), vol. 5: Herakles-Kenchrias (Zürich: Artemis Verlag, 1990), p. 307, no. 202<br>‘Perseus’, ‘Psoleas’, ‘Pygmaioi’, in Lexicon Iconographicum Mythologiae Classicae (LIMC), vol. 7: Oidipous-Theseus (Zürich: Artemis Verlag, 1994), p. 341, no. 153, p. 568, no. 2, pl. 435, p. 595, no. 2, pl. 467<br>‘Silenoi’, ‘Tritones’, in Lexicon Iconographicum Mythologiae Classicae (LIMC), vol. 8: Thespiades-Zodiacus (Zürich: Artemis Verlag, 1997), p. 1121, no. 111, p. 74, no. 7<br>Lezzi-Hafter, Adrienne, Cécile Jubier-Galinier, Leslie Threatte, Jan-Matthias Müller, and Kristine Gex, Potters - Painters - Scribes : Inscriptions on Attic (Zürich: Akanthus Verlag für Archäologie, 2016) <br>Lissarrague, Francois, ‘A Sun-Struck Satyr in Malibu’, Periplous: Papers on Classical Art and Archaeology Presented to Sir John Boardman, ed. by Gocha R. Tsetskhladze, A. J. N., W. Prag, and Anthony M. Snodgrass (London: Thames and Hudson, 2000), p. 192 n. 5<br>Mackay, Anne, ‘The Frontal Face and ‘You’. Narrative Disjunction in Early Greek Poetry and Painting’, Acta Classica. Proceedings of the Classical Association of South Africa, 44 (2001), p. 25 n. 36<br>Maffre, Jean-Jacques, ‘Collection Paul Canellopoulos (VIII): Vases béotiens’, Bulletin de Correspondance Hellénique, 99/1 (1975), p. 438 n. 92<br>Malagardis, Nassi-Athanasia. ‘Aparxai d'un ceramiste du temps de Nearchos au sanctuaire de la Nymphe’, in Griechische Keramik im kulturellen Kontext: Akten des Internationalen Vasen-Symposions in Kiel vom 24.-28.9.2001.Archäologische Institut der Christian-Albrechts-Universität zu Kiel, ed. by Bernhard Schmaltz and Magdalene Söldner (Münster: Scriptorium, 2003), pp. 32–4, fig. 3.3<br>Mertens, Joan R. ‘How to Read Greek Vases’ (New York: The Metropolitan Museum of Art, 2010), no. 9, pp. 13, 24, 62–5, 82<br>Mertens, Joan R. and Beth Cohen, ‘Attic White Ground: Potter and Painter’, The Colors of Clay: Special Techniques in Athenian Vases, ed. by Beth Cohen (Malibu: J. Paul Getty Trust, 2006), ed. pp. 187–88, 193, fig. 2, n. 14<br>Metropolitan Museum of Art, Greece and Rome  (New York: The Metropolitan Museum of Art, 1987), no. 21, pp. 10, 36<br>Metropolitan Museum of Art, ART = Discovering Infinite Connections in Art History (New York: Phaidon Press, 2020), pp. 069, 271<br>Moore, Mary B., ‘Sophilos and Early Greek Narrative’, Metropolitan Museum Journal, 51 (2016), pp. 16–17, fig. 9<br>Picón, Carlos A., Art of the Classical World in the Metropolitan Museum of Art: Greece, Cyprus, Etruria, Rome (New York: The Metropolitan Museum of Art, 2007), no. 81, pp. 82, 421<br>Platt, Verity. 2017. Introduction. The Frame in Classical Art : A Cultural History, Michael Squire, ed. pp. 174–75, fig. 3.10, Cambridge: Cambridge University Press.<br>Richter, Gisela M. A.,‘The Classical Collection: Rearrangement and Important Accessions’, Bulletin of the Metropolitan Museum of Art, 21/4 (1926), p. 10<br>Richter, Gisela M. A., Handbook of the Classical Collection (New York: The Metropolitan Museum of Art, 1930), p. 88, fig. 55<br>Richter, Gisela M. A., ‘An Aryballos by Nearchos’, American Journal of Archaeology, 36/3 (1932), 272–275<br>Richter, Gisela M. A., Handbook of the Greek Collection  Cambridge, Mass.: Harvard University Press, 1953), pp. 57, 197, pls. 37d, f.<br>Richter, Gisela M. A. and Marjorie J. Milne, Shapes and Names of Athenian Vases (New York: Plantin Press, 1935), p. 16, fig. 103<br>Robertson, Martin, A History of Greek Art (Cambridge: Cambridge University Press, 1975), pp. 129, 637 n. 122<br>Shaw, Carl A., Satyric Play: The Evolution of Greek Comedy and Satyr Drama (Oxford and New York: Oxford University Press, 2014), pp. 50–51, fig. 2.13<br>Sparkes, Brian, ‘Small World: Pygmies and Co.’,  World and Image in Ancient Greece, ed. by N. Keith Rutter and Brian A. Sparkes (Edinburgh: Edinburgh University Press, 2000), pp. 86–8, fig. 5.1<br>Von Bothmer, Dietrich and Alan L. Boegehold, The Amasis Painter and His World: Vase-Painting in Sixth-Century B.C. Athens (Malibu: J. Paul Getty Museum, 1985), pp. 39–40, fig. 21<br>Yatromanolakis, Dimitrios. 2016. Epigraphy of Art : Ancient Greek Vase-Inscriptions and Vase-Paintings pp. 30 n. 204, 67 n. 58, Oxford: Archaeopress.</p>",
    "Crediti": "<p style='font-size:18px;'><b>Credits</b><br><b>Author:</b> Vagelis Kolotsios<br><b>Image:</b> Metropolitan Museum of Art<br><b>Transcription:</b> Various sources (see Bibliography)</p>",
    "Autore": "<p align='right'><i>Vagelis Kolotsios</i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/2.png",
    "Type": "true",
    "id": 2
  },
  {
    "Sottotitolo": "tracce",
    "Titolo": "Literary Quotes in the Barrio <br>de las Letras <br>Madrid's Literary Quarter",
     "Image": "Immagini/tracce/traccia_3.png",
    "Descrizione": "<p>‘El Barrio de las Letras’ is a central neighbourhood of Madrid well-known, as the former home of writers of the Spanish Golden Age. In recent years this quarter has rendered homage to Spanish literature by adorning Huertas street with quotations from some the most recognized writers who lived here. This quotation references the play Don Juan Tenorio by José de Zorrilla, one of the most remarkable writers of Spanish Romanticism movement. Passing along the street, the floating words serve as permanent homage to the author and a quick glance through the greatest Spanish literature.<br></p>",
    "Descrizione2": "<p style='font-size:18px;font-style: italic;'>The ‘Barrio de las Letras’ is a neighbourhood filled with literature all around its streets reflecting the lives of the writers who once lived in it. Today, inscribed on the pavement, Huertas street showcases quotations from works of some of these writers. The decision to populate the streets with literary quotations was taken by the Ministry of Development in order to render homage to these writers and create a sense of collective identity.  The inclusion of quotations was part of a larger urban reform taking place in 2002 with the intention to revitalise and pedestrianise the quarter so that it could become one of the cultural landmarks in Madrid.<br>In addition to the passage from Don Juan Tenorio by José de Zorrilla (who was known to frequent the Romanticism Café in the neighbourhood), we can see the quotations from some of the greatest writers of Spanish Golden Age, such as Cervantes, Lope de Vega, Góngora, Quevedo all of whom lived and worked here at some point of their careers. Also, the inscription of Benito Perez Galdós recalls the locations of his stories, most centred in Madrid.<br>Everything in the neighbourhood resonates literature—from the Plaza Santa Ana, where the Spanish Theatre stands flanked by two sculptures of Calderón de la Barca and Federico Garcia Lorca, to the house-museums of Lope de Vega and Cervantes. Due to the literary activity that took part in these streets during the Spanish Golden Age, the first Corrales de Comedia of Madrid were installed here.<br>Today the “Barrio de las Letras” echoes its glorious past with the inscriptions and plaques set on the streets, but also through the enthusiastic cultural activities and organizations taking place. The neighbourhood is still the heart of the literary culture of Madrid with numerous theatres, cultural centres and literary cafes. </p>",
    "Dati_box": "<p style='font-size:18px;'><b>Location:</b> Spain, Madrid, Calle de las Huertas<br><b>Materials and Condition: </b>Laton inlay in the pavement<br><b>Date:</b> 2002<br><b>Language:</b> Spanish<br><b>Type of trace:</b> inscription<br><b>Transcription:</b> ¡Ah! ¿No es cierto ángel de amor que en esta apartada orilla más pura la luna brilla y se respira mejor?<br><b>Translation:</b> Oh, my angel of love, do you see that on this secluded shore the moon shines clear and pure and one breathes more easily?</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliography</b><br>Acosta Morales, Antonio, <i>La remodelación de la calle Huertas</i>, 356 (2004), 26-31<br>García Álvarez, Eva. <i>Inscripciones en el pavimento de la Calle Huertas de Madrid</i>, Ab initio, 3 (2015), 93-115<br>García Henche, Blanca and Salvaj Carrera, Erica <i>Barrios destino. El Barrio de las Letras de Madrid. Creación de una marca destino como estrategia de diferenciación de la oferta de turismo urbano</i>, Estudios turísticos, 215 (2018’) 39 – 60</p>",
    "Crediti": "<p style='font-size:18px;'><b>Credits</b><br><b>Image:</b> Laura Pastor<br><b>Transcription:</b> Laura Pastor<br><b>Translation of TRACE text:</b> N. K. Mayberry and A. S. Kline (The Project Gutenberg EBook)</p>",
    "Autore": "<p align='right'><i>Laura Pastor</i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/3.png",
    "Type": "true",
    "id": 3 },
    {
    "Sottotitolo": "tracce",
    "Titolo": "Tracce di Corsica a Roma",
     "Image": "Immagini/tracce/traccia_4.png",
    "Descrizione": "<p>Questa targa, collocata all’ingresso della Basilica di San Crisogono nel 2016, in occasione della Festa de’ Noantri, celebra il gemellaggio tra la chiesa e il popolo còrso, siglato nel 1445 come ringraziamento, da parte della città di Roma, ai caduti di guerra che avevano combattuto per la Santa Sede, e rafforzato nel 2014 con l’annuale messa in lingua còrsa nella basilica, che è a tutti gli effetti la Chiesa nazionale dei Corsi.<br></p>",
    "Descrizione2": "<p style='font-size:18px;'>Il còrso è una lingua romanza riconosciuta nel 1859. La Corsica ospitò nel tempo diverse varietà romanze, che confluirono in una lingua che conserva tratti tipici del toscano, del sardo settentrionale, dei dialetti italiani meridionali, o addirittura dell’Italia del nord.<br>L’iscrizione incisa su questa lastra attesta l’esistenza di una norma e di un canone che rendono il còrso adatto alla scrittura ufficiale e al registro burocratico e celebrativo. </p>",
    "Dati_box": "<p style='font-size:18px;'><b>Luogo:</b> Italia, Roma, all’ingresso della Basilica di San Crisogono, Piazza Sidney Sonnino, 44<br><b>Materiali e conservazione:</b> Iscrizione su marmo in buono stato.<br><b>Data:</b> 23/7/2016<br><b>Lingua:</b> Còrsa<br><b>Trascrizione della targa:</b> A Basilica San Crisogono hè a Chjesa Naziunale di i Corsi da 1445 diventa locu di sepoltu di Officiali è Suldati Corsi di a Guardia Pontificale à u serviziu di a Santa Sede. In u 1505 i marinari Corsi di Trastevere trovanu vicinu à e coste laziale una statua riprisintante la Madonna del Carmine è a mettenu in una cappella di a Madonna del Carmine in Basilica di San Crisogono. In u 1543 con l’auturisazione di u Papa Paulu III i membri di a milizia corsa stabiliscenu la Confraternita del SS.mo Corpo e della glorissima Vergine Mater Dei del Carmine<br>23-7-2016<br>Associazione culturale guardia corsa papale in San Crisogono<br><b>Traduzione della trascrizione:</b>‘La Basilica di San Crisogono è la chiesa nazionale dei corsi dal 1445 diventa luogo di sepoltura di ufficiali e soldati corsi della guardia potificia a servizio della Santa sede. Nel 1505 i marinai còrsi di Trastevere trovano vicino alle coste laziali una statua rappresentante la Madonna del Carmine e la mettono nella cappella della Madonna del Carmine nella basilica di San Crisogono. Nel 1543 con l’autorizzazione del papa Paolo III i membri della milizia corsa stabiliscono la confraternita del santissimo corpo e della Gloriosissima “Vergine Mater Dei del Carmine”.<br>23-7-2016<br>Associazione culturale guardia corsa papale in San Crisogono’</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliografia</b><br>‘Targa in memoria della decisione di rendere San Crisogono Chiesa Nazionale dei Corsi’, Rerum romanarum, ottobre 2017<br>Vitolo, Giuseppe, ‘La lingua corsa e i dialetti d’Italia: aspetti morfologici in comune’, Corsica Oggi, 31 maggio 2017<br>Vitolo, Giuseppe, ‘La lingua còrsa riassume in sé le parlate locali di tutta l’Italia’, Corsica oggi, 16 novembre 2016</p>",
    "Crediti": "",
    "Autore": "<p align='right'><i>Giorgio Margiotta, Gaia Naplone, Emanuela Maura, <br>Flavia Vicol, Martina Necci</i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/4.png",
    "Type": "true",
    "id": 4 }, 
       {
    "Sottotitolo": "tracce",
    "Titolo": "Le targhe dei mondezzari",
     "Image": "Immagini/tracce/traccia_5.png",
    "Descrizione": "<p>Con il termine ‘targhe dei mondezzari’ ci riferiamo ad alcune iscrizioni su marmo affisse per le strade di Roma nel corso del XVIII/XIX secolo. Tramite queste targhe venivano presentati gli editti del Monsignore Presidente delle strade, funzionario della Curia Romana e dirigente del ‘tribunale delle strade’, giurisdizione soppressa nel 1816 che fino a quel momento si era occupata proprio dell’amministrazione delle vie della città.<br></p>",
    "Descrizione2": "<p style='font-size:18px;'>Il problema della gestione dei rifiuti a Roma è non solo annoso, ma secolare: nel XVIII/XIX secolo era abitudine comune a tutti i cittadini romani sbarazzarsi dell’immondizia gettandola in strada. I rifiuti venivano abbandonati anche per lunghe settimane, e portati via solo quando se n’era creato un cumulo sufficientemente grande, il così detto ‘mondezzaro’. L’enorme quantità d’immondizia contribuiva al deterioramento della già precaria situazione igienico-sanitaria della città, che veniva peggiorata dal fetore che da tali cumuli si spandeva anche a grande distanza, attirando diversi animali randagi.<br>Tale condizione portò all’introduzione di una serie di vere e proprie leggi, di cui si dava notizia alla popolazione tramite delle targhe di marmo affisse proprio nei luoghi dove erano soliti crearsi i ‘mondezzari’. Il deterrente era, nella maggior parte dei casi, una multa in ‘scudi’ per i trasgressori, talvolta accompagnata da una pena corporale e, nel caso di vicinanza ad una chiesa, anche dalla scomunica.<br>Per quanto riguarda la lingua, è peculiare, nel termine ‘mondezzaro’, la scelta di un suffisso diverso dal fiorentino e dall’italiano standard. Infatti, pur trattandosi di linguaggio giuridico, viene utilizzata la variante non toscana, che agisce secondo il suffisso -aro, presente nelle voci del Centro Meridione, ma anche e soprattutto a Roma. Si veda, inoltre, il contrasto tra l’uso della parola ‘immondezza’ e ‘immondizia’. ‘Immondezza’ compare nella targa in Piazza di Trinità dei Pellegrini, la prima in esposizione, datata 1688. Il plurale ‘immondezze’ compare anche nella seconda targa, situata in Vicolo della Luce e datata 1763; lo stesso dicasi per la terza targa, situata in via dei Cappellari e datata 1733. Nella quinta targa, datata 1746 e situata in Via in Pubblicolis, compare invece la variante ‘immondizie’. Non è quindi un fenomeno da considerare in diacronia, ma semplicemente una scelta arbitraria circa la variante da applicare. Il fenomeno che ha poi portato la parola ‘immondizia’ a stabilirsi nello standard della lingua italiana è da ricercarsi nelle mutazioni del vocalismo tonico: si tratta dell’anafonesi, fenomeno fonetico tipicamente fiorentino per cui le vocali toniche ‘é’ e ‘ó’ si chiudono rispettivamente in ‘ì’ e ‘ù’ quando seguite da determinate consonanti, come ad esempio nel nesso nasale + velare (vinco < venco) o in nessi consonanti palatali. Nel caso di ‘immondizia’, rispetto a ‘immondezza’, si è stabilita la chiusura della é tonica in ì, seguita dal nesso /ts/, sempre geminato tra vocali, e a sua volta seguito dall’approssimante palatale sonora /j/. La trascrizione standard corrisponderebbe quindi a [immon’dit.tsja].<br>Doveroso, infine, soffermarsi sulla quinta targa (Via in Pubblicolis, 1746). Qui la forma imperativa negativa della III persona singolare del verbo ‘ardire’ viene coniugata secondo la norma: ‘che non ardisca’. La forma plurale del verbo dovrebbe essere quindi, per analogia, ‘ardiscano’, ma appare invece come ‘ardischino’. Tale forma rappresenta una deviazione dallo standard e presenta sonorità romanesche.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Luogo:</b> Italia, Roma, <br><i>Targa 1:</i> Piazza Trinità dei Pellegrini, Rione VII Regola, Roma, RM.<br><i>Targa 2:</i> Vicolo della Luce, Rione XIII Trastevere, Roma, RM.<br><i>Targa 3:</i>Via dei Cappellari, presso l’arco di Santa Margherita, Rione VI Parione, Roma, RM.<br><i>Targa 4:</i> Palazzo De Carolis, Via Lata, Rione IX Pigna, Roma, RM.<br><i>Targa 5:</i>Via in Publicolis, Rione XI Sant’Angelo, Roma, RM.<br><b>Materiale:</b>Marmo<br><b>Data:</b> XVIII secolo<br><b>Lingua:</b> Italiano/Dialetto romanesco</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliografia</b><br>Curiosità romane. Le targhe dei ‘mondezzari’,[1 giugno 2003]<br>‘La monnezza de Roma è un problema antico’, Roma.com, 29 agosto 2020, [1 giugno 2003]<br>Rendina, Claudio, La Repubblica, 21 settembre 2003, [1 giugno 2003]<br>Rerum romanorum, [1 giugno 2003]</p>",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Immagini: </b>www.info.roma.it</p>",
    "Autore": "<p align='right'><i>Flavia Cotroneo , Giulia Tavella, Maria Francesca Sorrentino </i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/5.png",
    "Type": "true",
    "id": 5 },
         {
    "Sottotitolo": "tracce",
    "Titolo": "The National Covid Memorial Wall",
     "Image": "Immagini/tracce/traccia_6.png",
    "Descrizione": "<p>Strategically positioned on the wall that backs onto St Thomas’ Hospital, the National Covid Memorial Wall (the ‘Covid Wall’) is a stark reminder of the immense loss of life due to the Covid 19 pandemic. Volunteers painted 150,000 hearts on the wall facing the Houses of Parliament across the river Thames and asked anyone affected by a bereavement to write their own tribute in one of the hearts. The wall is 500 metres in length with dedications in numerous languages and scripts, representing the multicultural population of London and regions further afield.</p>",
    "Descrizione2": "",
    "Dati_box": "<p style='font-size:18px;'><b>Location:</b> United Kingdom, London, Albert Embankment<br><b>Dimensions:</b> c. 500m.<br><b>Materials and Condition:</b> Paint and marker pens on stone wall – liable to deterioration<br><b>Date:</b> March 2021 to present<br><b>Language:</b> Multiple<br><b>Writing system(s) and Script(s):</b> Multiple<br><b>Type of trace:</b> (list one) graffito<br><b>Transcription Plaque:</b>THE NATIONAL COVID MEMORIAL WALL + c. 150,000 tributes and personal messages</p>",
    "Bibliografia": "",
    "Crediti": "<p style='font-size:18px;'><b>Credits</b><br><b>Images: </b>Mary Wardle</p>",
    "Autore": "<p align='right'><i>Mary Wardle</i></p>",
    "Mappa": "Immagini/Mappa/mappa1.png",
    "File": "Immagini/Proverbi/6.png",
    "Type": "true",
    "id": 6 },
           {
    "Sottotitolo": "tracce",
    "Titolo": "Resistenza a Villa Gordiani",
     "Image": "Immagini/tracce/traccia_7.png",
    "Descrizione": "<p>Lungo viale Venezia Giulia, nel quartiere romano di Villa Gordiani, si trova un murale corredato di un’iscrizione nella parte superiore destra e di una dedica in basso a sinistra. Il disegno ritrae tre fucilieri partigiani su un tetto. La dedica reca il nome di un attivista scomparso, e l’iscrizione richiama la propaganda partigiana attraverso l’invito alla lotta. L’iscrizione ‘La Resistenza non è finita’ è il cuore di questa traccia linguistica: si stabilisce una connessione tra la lotta partigiana e la lotta civica. </p>",
    "Descrizione2": "<p style='font-size:18px;'>L’invito, rivolto a coloro che si sentono dimenticati dalle istituzioni – specie nella difficile realtà della periferia romana – è quello di far sentire la propria voce. La connessione è stabilita dalla scritta e dal simbolo dell’ottava zona partigiana, di cui il quartiere fu parte, e la si ritrova nella tradizione di militanza antifascista che ancora oggi costituisce un vanto e un fondamento per molti suoi abitanti. Il nome dell’attivista scomparso è così una dedica, che rende questa traccia un epitaffio, e nel contempo fornisce a chi legge l’esempio di chi ha incarnato questo messaggio.<br>L’iscrizione compare nel 2019, sei anni dopo la scomparsa di Mario Cordella, attivista noto nell’ambiente, e dedicatario dell’iscrizione.<br>‘La Resistenza è storia, ma anche mito; ovvero, storia trasfigurata in mito. Nel linguaggio comune il termine “mito” è usato come sinonimo di favola, ma nelle civiltà antiche aveva il compito di rappresentare in veste allegorica l’atto di nascita di una forma di organizzazione sociale, di un sistema politico. Quello della Resistenza a Villa Gordiani è un mito fondativo’ celebrato ancora oggi non solo come preziosa memoria da custodire, ma come presenza attuale, diffusa nell’immaginario collettivo di quartiere. Attraverso il murale, la Resistenza esce dalla storia e rivive nel presente, nel sentimento di insofferenza e protesta civica di questa particolare area della periferia romana. Così, il memoriale è anche definizione identitaria del quartiere.<br>Il graffito assume la forma dello slogan politico, e invita il fruitore a combattere per i propri diritti. Con un ‘tu impersonale’ l’iscrizione si rivolge al passante costituendo un memento e diffondendo un messaggio di ribellione che riecheggia nelle numerose iscrizioni e striscioni in cui è possibile imbattersi nella zona. Un altro stilema riconoscibile è quello della rima, che insieme alla brevitas rende il messaggio immediato e d'impatto, e lo colloca nell'ambito dei molti fenomeni linguistici urbani a sfondo ideologico. In terzo luogo, risalta l'utilizzo di un preciso campo lessicale, quello della lotta, che permea l'attivismo politico. Sono queste, insieme alla metafora – che trasporta l'immaginario della lotta partigiana su un piano civico –, le caratteristiche linguistiche che rimandano a una specifica tipologia testuale, di cui fanno parte i modelli dello slogan pubblicitario, del manifesto politico e degli striscioni. <br>Ci troviamo di fronte a un fenomeno riconoscibile, che si intreccia a una tradizione particolare di quartiere.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Luogo:</b> Italia, Roma, Viale Venezia Giulia, 55. Facciata laterale dell’edificio<br><b>Dimensioni:</b> Iscrizione principale: ca. 3,00 x 1,00 m<br><b>Dedica: </b>ca. 3,50 x 0,30 m<br><b>Disegno:</b> ca. 9,00 x 4,00 m <br><b>Materiali e conservazione:</b> Vernice acrilica su intonaco. Stato di conservazione ottimo.<br><b>Data:</b> 2019<br><b>Lingua/e:></b> Italiano<br><b>Sistemi scrittori e scritture:</b> Alfabeto latino. Caratteri maiuscoli.<br><b>Trascrizione:</b> Iscrizione principale: La Resistenza non è finita / alza la testa / combatti per la tua vita<br><br>Ciao compagno Mario Cordella</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliografia</b><br>Ferdinando Pappalardo, 'Il paesaggio partigiano nel mito fondativo della Resistenza', Patria Independente, n. 107, 2020.>br>Stefania Ficacci, ' La Resistenza alla borgata Gordiani', Ecomuseo Casalino</p>",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Immagini:</b> Giulia D’Elia, Alessandro Pasquini.</p>",
    "Autore": "<p align='right'><i>Giulia D’Elia, Alessandro Pasquini</i></p>",
    "Mappa": "Immagini/Mappa/mappa7.png",
    "File": "Immagini/Proverbi/7.png",
    "Type": "true",
    "id": 7 },
           {
    "Sottotitolo": "tracce",
    "Titolo": "Il Libro di Giuditta nella Sainte Chapelle - Parigi",
     "Image": "Immagini/tracce/traccia_8.png",
    "Descrizione": "<p>La Sainte-Chapelle conta in totale quindici finestre con vetrate, otto lungo la navata, quattro per lato e sette nella zona del coro. Per svolgere questa analisi si sono prese in esame le vetrate rappresentanti le scene dal Libro di Giuditta, tra le poche a possedere un apparato didascalico. Tra i quaranta pannelli relativi a Giuditta troviamo solo dieci didascalie, tutte descrittive e in volgare.</p>",
    "Descrizione2": "<p style='font-size:18px;'>Prendendo in esame tutte le didascalie che troviamo nel complesso delle vetrate della Sainte-Chapelle possiamo notare come siano sicuramente organizzate in maniera non sistematica e né omogenea, dal momento che a fronte di millenovecentosette pannelli figurativi solamente trentasette presentano delle didascalie. Di queste trentasette solo dieci sono redatte in lingua volgare, quelle della vetrata D prese in esame qui. Viene fatta un’eccezione per una probabile iscrizione volgare individuata da Grodecki nel ciclo di vetrate M, che vedrebbe un pannello raffigurante Mosè e altri uomini sollevare l’Arca dell’Alleanza, sulla quale si leggerebbe la scritta role, appunto “rotolo” (delle leggi).<br>A questo aspetto di non sistematicità si aggiunge un altro aspetto, ovvero quello della non leggibilità di tali iscrizioni. Infatti, se consideriamo le didascalie per dove sono collocate e le osserviamo senza l’ausilio di strumenti che ci permettono di ingradirle, dobbiamo constatare che è molto complicato notare le didascalie e quasi impossibile leggerle in condizioni normali.<br>Non potendo non tenere conto di questi elementi, dobbiamo considerare il carattere costitutivo di tali didascalie, che venivano probabilmente percepite come elemento essenziale all’interno dell’immagine. <br>L’importanza di questa traccia è data dalla collocazione di queste didascalie descrittive volgari, ovvero la Sainte-Chapelle, fatta costruire da Luigi IX per custodire la corona di spine, un frammento della Croce e molte altre reliquie legate alla Passione. Ne consegue che la scelta di utilizzare, per alcune di queste iscrizioni, la lingua francese è in qualche modo inattesa. Come fa notare Perrot, l’utilizzo del volgare nella Francia del 1200 non è cosa nuova – lo si ritrova anche impiegato su carte diplomatiche; la novità è il suo utilizzo all’interno di un’opera d’arte monumentale, e per giunta all’interno di un monumento reale.<br>La loro distribuzione frammentaria e non programmatica ci spinge a riflettere sullo status della scrittura dell’epoca, sicuramente appannaggio di pochi sia nella sua esecuzione che nella sua comprensione. L’ipotesi avanzata da numerosi studiosi, tra i quali Petrucci e Perrot, è che le didascalie siano state copiate, insieme alle stesse immagini, da qualche sommario volgare non ancora identificato. Si ipotizza, quindi, che la ragione della presenza di tali iscrizioni possa essere attribuita a un tipo di copiatura soltanto inerziale, ma può anche trattarsi, come sottolinea Petrucci, di una didascalia percepita come costitutiva dell’identità dell’immagine.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Luogo:</b> Francia, Parigi, 10 Bd du Palais, 75001 Paris<br><b>Dimensioni:</b>Ogni vetrata misura 15 metri d’altezza<br><b>Materiali e conservazione:</b> Vetro policromo<br><b>Data:</b> 1243/1248<br><b>Lingua/e:</b> Francese antico<br><b>Sistemi scrittori e scritture:</b> Maiuscola gotica</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliografia</b><br>Grodecki et alii, Les vitraux de Notre-Dame et de la Sainte-Chapelle de Paris (Paris: CNMH-CNRS, 1956)<br>Perrot, Françoise, ‘Les iscriptions en français du vitrail de Judith à la Sainte Chapelle de Paris’, in Épigraphie et iconographie. Actes du Colloque tenu à Poitiers les 5-8 octobre 1995 sous la direction de Robert Favreau (Poitiers: CESCM, 1996), pp. 193-99<br>Petrucci, Livio, Alle origini dell’Epigrafia Volgare, Iscrizioni italiane e romanze fino al 1275 (Pisa, Pisa University Press, 2016)<br></p>",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Immagini:</b> Denis Krieger </p>",
    "Autore": "<p align='right'><i>Elisa Gregorio</i></p>",
    "Mappa": "Immagini/Mappa/mappa8.png",
    "File": "Immagini/Proverbi/8.png",
    "Type": "true",
    "id": 8 },
           {
    "Sottotitolo": "tracce",
    "Titolo": "Undeciphered Writing <br> Disk of Phaistos",
     "Image": "Immagini/tracce/traccia_9.png",
    "Descrizione": "<p>The Phaistos Disk was found in 1908 at the ruins of the First Minoan Palace of Phaistos in Crete, Greece. The exact date of the disk is uncertain, but it probably dates from the MM IIB period (17th c.B.C.). Its mysterious inscription constitutes 242 signs, 123 on side A and 119 on side B, in spiral order. There appear 45 distinct signs (with repetitions), that were impressed on wet clay before the disk was fire-hardened. The signs probably belong to a Cretan syllabic script, which has not yet been deciphered despite the numerous attempts over the years, using the most diverse methods of study. Researchers have proposed widely diverse speculations about the purpose, the contents of its inscription and its creators.</p>",
    "Descrizione2": "<p style='font-size:18px;'><MI>The disk constitutes the most famous inscription of the Minoan civilization, a sample of Cretan hieroglyphic writing, possibly syllabic. “Dated circa 1,700 BC,  it belongs to the period of Minoan Writing, but differs in many ways from it. The writing on the disc was inscribed in the clay using different stamps and is one of the oldest methods of writing, about 2,500 years before the first samples of printed materials.<br>The Disc is inscribed on both sides with a total of 242 tokens, divided into 61 groups. There are 45 distinct signs on the disc, more than necessary for an alphabet but fewer than necessary for a true ideographic script. (EKT)</MI><br><br>In several places there are traces of scribal corrections. Some symbols have been compared with Linear A characters, while other scholars have pointed to resemblances with  Anatolian hieroglyphs or  Egyptian hieroglyphs (Wikipedia). The signs on the disk depict recognizable objects, like human forms, fish, birds, plants, ships, hand tools, vessels etc. These shapes were stamped using  seals when the clay was still damp, and this is the reason why the Disk is considered to be the earliest known example of typography. It is unlikely that seals would be made for single use only, and  in addition to being of interest in itself, this object therefore testifies to an established use of this now undecipherable script, and to the many other stamped or written inscriptions in that form that have been lost in the intervening millenia. It is thought that the Phaistos Disk would be read spirally, that is from its circumference to its center, However, despite many researchers’ attempts, the signs (and language) of the Disk have not been deciphered, and many different meanings have been ascribed to the inscribed object, from it being related to religion, a story, a geometric theorem to the object functioning as a calendar. Some of the signs that appear on the Disk have been found on a late MInoan axe discovered at Arkalohori, Crete. It is thought that the signs on this axe had an astronomical reference.<br>Although the Phaistos Disc is generally accepted as authentic by archaeologists, a few scholars believe that the disc is a forgery or a hoax.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Location:</b> Greece, Crete, Festos , currently at Archaeological Museum in Heraklion, Crete, Greece<br><b>Dimensions:</b> average diameter 16 cm and 2.1 cm thick<br><b>Materials and Condition:</b> clay<br><b>Date:</b> found 3rd of July in 1908,  probably dating from the 17th c. B.C.<br><b>Language:</b> Cretan syllabic script<br><b>Writing system(s) and Script(s):</b> Cretan syllabic script<br><b>Type of trace: </b>(list one) speaking object, disk</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliography</b><br>Bennett, Emmett L., ‘Aegean Scripts’, The World's Writing Systems, ed. by Peter T. Daniels and William Bright (Oxford: University Press, 1996), pp. 125-133<br>EKT National Document Centre, ‘The voice of the Phaestos disk’, <br>FORTH. Foundation for Research and Technology - Hellas, ‘The Disk of Phaestos’, <br>Heraklion Archaeological Museum, ‘The Phaestos Disk’, <br>‘Phaistos Disc’, Wikipedia,  <https://wiki2.org/en/Phaistos_Disc> <br>Sakellarakis Ι.Α., Museum of Herakleion (Athens, 2003), 30-31<br>Vasilakis, Αdonis, Herakleion Archaeological Museum of Iraklio (Athens: Adam Editions, 2000)<br></p>",
    "Crediti": "",
    "Autore": "<p align='right'><i>Stella Konstantaki</i></p>",
    "Mappa": "Immagini/Mappa/mappa9.png",
    "File": "Immagini/Proverbi/9.png",
    "Type": "true",
    "id": 9 },
            {
    "Sottotitolo": "tracce",
    "Titolo": "Column of St Zenobius",
     "Image": "Immagini/tracce/traccia_10.png",
    "Descrizione": "<p>The column of St. Zenobius, located on the northern side of the Florentine baptistry, marks both a sacred miracle and a moment when oral tradition took material form. The column you see today is a palimpsest of language and materials whose origins belong to a shadowy period between the 5th and 9th c. when legends circulated about a tree that was revived on the site though contact with St. Zenobius’ relics. The column, victory cross, and inscriptions represent those oral [link to orality] legends, and they influenced textual versions of the saint’s legend </p>",
    "Descrizione2": "<p style='font-size:18px;'>In early medieval Florence, hagiographical legends circulated surrounding the city’s first saint, St. Zenobius. Lorenzo, Archbishop of Amalfi, who wrote in the 11th c. the earliest extant biography of the saint, aside from a few words by St. Ambrose’s biographer, Paulinus, had to rely on the testimonies of ‘pious persons’ whom he met during his Florentine sojourn, other documentation on the saint having been lost in fire. He recounts the posthumous miracle of the translation of St. Zenobius’ body from its original sepulchre at the church of San Lorenzo—still then outside of the city walls—to the then cathedral of Santa Reparata (eventually replaced on the same site with the current cathedral of Santa Maria del Fiore, foundation stone, 1296). It was while being translated, that the saint’s body touched the dead tree near the baptistery on the square which subsequently grew leaves and flowers. <br>Notice of the miraculous [link miracle] event probably originates in the 9th c. under Florentine bishop Andrea, an important figure for the construction of the baptistery and the Carolingian renewal of the cathedral complex, as bishop Andrea is mentioned in the sources, though an earlier 5th c. bishop Andrea is recorded in some St. Zenobius biographies, giving rise to the translation dates of 431 CE and 409 CE within the inscriptions and the traditional translation date of 26 January 429 CE.<br>The column which stands in for the tree was probably erected on this site in conjunction with translation feast day processions documented by the first half of the 13th c., and certainly well before the 14th c. when the Florentine historian, Giovanni Villani, notes that the column fell during the flood of 1333 and had to be re-erected by the corporation in charge of the baptistry—which they did in 1334, adding the cross in 1338, and the iron crown and tree in 1375. <br>It is unknown when the two inscriptions on the body of the column and near the crown, which differ in details and commemorative date, were carved, though it is likely that shorter one near the crown dates from the (re)placing of the cross in 1338 and the latter from about 1375. The cross on top is a 21st c. replica of the replacement cross of 1834 by Giovanni Sandrini, executed as part of a conservation campaign, itself a replacement of a Renaissance subsitution from the turn of the 16th c.</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Location:</b> Italy, Florence, Piazza di San Giovanni, north of the baptistery <br><b>Materials and Condition:</b> Marble with iron elements. Contains some erosion to the inscription and a replacement cross (see text)<br><b>Date:</b> 13th c. – 14th c. <br><b>Language:</b> Latin<br><b>Writing system(s):</b> Roman Alphabet, Capital Letters<br><b>Transcription:</b> Around the top of the column: H(IC) ARBOR SICCA FLORVIT TACTU CORPORIS S(ANCTI) ZENOBII EP(SCOP)I FLOR(ENTINORUM) A.D.CCCCXXXI DIE VII JAN(UARII) [This dead tree flowered by touching the body of St. Zenobius, Bishop of Florence, the year of our Lord, 7 January 431]<br>Carved on the column: ANNO AB INCARNATIONE D(OMI)NI CCCC VIIII DIE XXVI JANUARII TEMPORE IMPERATORUM ARCHADII ET HONORII ANNO XI FERIA QUINTA. DUM DE BASILICA S(AN)C(T)I LAURENTII AD MAIOREM ECCLESIAM FLORENTINAM CORPUS S(AN)C(T)I ZENOBI FLORENTINORUM EPISCOPI FERETRO PORTARETUR ERAT  HIC IN LOCO ULMUS ARBOR VT ARIDA TUNC EXISTENS QUAM CUM FERETRUM S(AN)C(T)I CORPORIS TETIGESSET SUBITO FRONDES ET FLORES MIRACULOSE PRODUXIT IN CUIUS MIRACULI MEMORIA CRISTIANI CIVESQUE FLORENTINI IN LOCO SUBLATE ARBORIS HIS HANO COLUPNAM CUM CRUCE IN SIGNO NOTABILI EREXERUNT. [The year of the Incarnation of our Lord Thursday 26 January 409, in the eleventh year of the reign of emperors Arcadius and Honorius ….]</p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliography</b><br>Acta Sanctorum XIX (Paris, 1865), pp. 49-69<br>Benvenuti, Anna, ‘Stratigrafie della memoria: scritture agiografiche e mutamenti architettonici nella vicenda del “Complesso cattedrale’ fiorentino”’, in Il bel San Giovanni e Santa Maria del Fiore. Il centro religioso di Firenze dal Tardo Antico al Rinascimento, ed. Domenico Cardini (Florence, 1996), pp. 95-127<br>Ciandelli, Alessandro, San Zanobi. Vita, reliquie, culto, iconografia (Florence, 2005)<br>Cocchi, Arnaldo, Le chiese di Firenze dal secolo IV al secolo XX, vol. 1: Quartiere di San Giovanni (Firenze, 1903), pp. 48-53<br>Lorenzo da Amalfi, ‘Vita sancti Zenobii episcopi’, in La vita di San Zanobi, vescovo fiorentino volgarizzamento del buon secolo della vita toscana, altra di F. Gio. Maria Tolosani inedita, quelle di Lorenzo archivescovo d’Amalfi e di Clemente Del Mazza e la storia in ottava rima scritta da Bernardo Giambullari, si aggiunge La vita di S. Antonio arcivescovo dello stesso F. Gio. M. Tolosani (Florence, 1863), pp. 34-42 <br>Paulinus Mediolanensis, Vita sancti Ambrosii (Washington DC, 1928)<br>Villani, Giovanni, Nuova cronaca, ed. by G. Porta (Parma, 1991)<br></p>",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Images:</b> Column of San Zenobius, Firenze, fotografia del 2012 (Wikimedia commons); Ridolfo Ghirlandaio, Conveyance of the Body of Saint Zenobius, 1516 (Galleria dell’Accademia, Firenze). Davide Ghirlandaio, Sepoltura di San Zanobi, c. 1479 (Metropolitan Museum, New York, “dominio pubblico”)</p>",
    "Autore": "<p align='right'><i>Maia Wellington Gahtan</i></p>",
    "Mappa": "Immagini/Mappa/mappa10.png",
    "File": "Immagini/Proverbi/10.png",
    "Type": "true",
    "id": 10 }, 
            {
    "Sottotitolo": "tracce",
    "Titolo": "Fontana Priuli. Venice and Turkey in Crete",
     "Image": "Immagini/tracce/traccia_11.png",
    "Descrizione": "<p>Priuli Fountain or Fontana Nuova is located at Delimarkou Street, behind the Bodossakio School and opposite the Venetian gate of Dermatas in Herakleion, Crete. It was built near the end of the great siege of Candia (1648-1669), after the Ottoman besiegers interrupted the city’s main water supply. The particularity of this fountain stands in the fact that there are two epigraphs on it, one in Latin and the other in Ottoman Turkish. The fountain and its inscriptions is thus a trace of the two governing populations at the moment of transition from one to another – the Latin-writing (but Venetian or other  Italian dialects -speaking) Venetians, and the recently invading Ottoman Turks, with their characteristic script.  Cretan Greek and other languages that may have been spoken by many inhabitants of the island at this time are not represented on this monument.</p>",
    "Descrizione2": "<p style='font-size:18px;'>During the siege of the Khandax (city of Herakleion, Crete), the Ottomans cut off the supply pipe to the Morosini Fontana, leaving the city dry. It was then that the Venetian General Antonio Priuli discovered underground water in a defensive ditch outside the Bethlehem Bastion, but within the city walls. He diverted it to the Dermata Gate and in around 1666 he constructed the fountain which bears his name. The fountain, which is decorated with four columns and Corinthian pilasters with a triangular pediment was also known as Fontana Nuova, and in the Ottoman period as the Delimarkos fountain.<br>One of the first concerns of the Venetian leadership (which lasted from the 13th to the 17th c.) was the supply of water to the thirsty city of Chandakas, which was lacking in spring water. This was accomplished with the construction of cisterns and wells, public and private.  Εspecially during the last centuries of the Venetian leadership, the rulers were eminently interested in solving the matter of water supply of the city, so that water could be ensured in case of siege. There is no official’s report from the Kingdom of Crete to the Central Government of Venice that does not emphasize the abject situation of the city regarding the water supply problem. They all stress the fact that there is shortage of good potable water and underline its significance in case of war. Various elaborately decorated fountains of the period are preserved and ornament the old city of Herakleion.<br>The ‘General Provisioner’ Antonio Priuli constructed the Fontana Nuova in 1666 and mentions its construction in his report (Spanakis 1976 pp. 19-22 and 50). The fountain is decorated with round and square columns with Corinthian type capitals, while a triangular pediment crowns the whole construction. From both sides of the columns there are niches with their metopes elaborately decorated. In the middle of the fountain there is a Turkish inscription, and under it a Latin one. The Priuli Fountain was renamed Delimarkou or Delimarkos Fountain (Karantzikou 1999, p. 27) during the Ottoman period (1669-1898). An Ottoman inscription was placed over the Latin  one, stating that the fountain had dried up but under the care of the beneficent Gazi Hüseyin Paşa [leader of the Ottoman forces in Crete], it was supplied with water again (Stavrinidis 1971, p. 30).<br></p>",
    "Bibliografia": "<p style='font-size:18px;'><b>Bibliography</b><br>‘Η Κρήνη του ανύπαρκτου Δελημάρκου που έκανε τους Τούρκους να το βάζουν στα πόδια’;<br>Mackridge, Peter, The Crete of R. M. Dawkins (1903-1919) (Oxford: Oxford University Press, 2020);<br>‘Priuli or Delimarku’, Water in Crete: Water resources and uses of water in Crete of the Venetian and Ottoman period;<br>Spanakis S., The water supply to Herakleion: 828-1939 (Herakleion: Technical Chamber of Greece – Department of  Eastern Crete, 1981), pp. 86-88;<br>Spanakis S., Monuments of the Cretan History, vol. VI, I relazione di antonio Priuli, Provveditor Generle delle Armi in Candia (Herakleion, 1976);<br>Stavrnidis, N., Capetan Michalis Korakas and his comrades In arms (Herakleion, 1971), p.30</p>",
    "Autore": "<p align='right'><i>Stella Konstantaki</i></p>",
    "Mappa": "Immagini/Mappa/mappa11.png",
    "File": "Immagini/Proverbi/11.png",
    "Type": "true",
    "id": 11 }, 
            {
    "Sottotitolo": "tracce",
    "Titolo": "Football rules in Cambridge",
     "Image": "Immagini/tracce/traccia_12.png",
    "Descrizione": "<p>Bearing engravings of the 11 rules of football, set down in 1848 and commonly known as the <i>Cambridge Rules</i>, this granite monument was commissioned by Cambridge City Council as a piece of public art and unveiled in 2018. One large granite stone was cut into nine equal pieces with four pieces forming the permanent monument on Parker’s Piece, a large green area where the first game regulated by these rules is said to have been played. The Cambridge monument presents the rules in English, with fragments in six other languages.  The other five have been sent as ‘tokens of exchange’ to Shanghai (China), Rio de Janeiro (Brazil), Chennai (India), Cairo (Egypt) and Mombasa (Kenya), echoing how football has grown to encompass race, nation, class, gender and languages. </p>",
    "Descrizione2": "<p style='font-size:18px;'>The languages and scripts of the engravings reflect the global sites of the stones, with the addition of Russian (the project is partnered by the Street Child United charity who, in 2018, were holding their World Cup event in Moscow). On each different international site, the rules appear in full in the local language, and fragments in the other languages have been included.  The rules, originally recorded by a group of university students, are generally recognized for their influence over the modern game across the world</p>",
    "Dati_box": "<p style='font-size:18px;'><b>Location:</b> United Kingdom, Cambridge, Parker’s Piece <br><b>Materials and Condition:</b> Granite <br><b>Date:</b> 2018<br><br><b>Dimensions:</b> c. 3.5m tall<br><b>Language:</b> English, Arabic, Chinese, Portuguese, Russian, Swahili, Tamil<br><b>Writing system(s):</b> Latin, Arabic, Chinese characters, Cyrillic, Tamil<br><b>Transcription:</b> <p><span >1848</span></p><p>The Laws of the University Foot Ball Club</p><ol type="1" style="margin:0pt; padding-left:0pt"><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>This club shall be called the University Foot Ball Club.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>At the commencement of the play, the ball shall be kicked off from the middle of the ground: after every goal there shall be a kick-off in the same way</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>After a goal, the losing side shall kick off; the sides changing goals, unless a previous arrangement be made to the contrary.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>The ball is out when it has passed the line of the flag-posts on either side of the ground, in which case it shall be thrown in straight.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>The ball is behind when it has passed the goal on either side of it.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>When the ball is behind it shall be brought forward at the place where it left the ground, not more than ten paces, and kicked off.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>Goal is when the ball is kicked through the flag-posts and under the string.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>When a player catches the ball directly from the foot, he may kick it as he can without running with it. In no other case may the ball be touched with the hands, except to stop it</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>If the ball has passed a player, and has come from the direction of his own goal, he may not touch it till the other side have kicked it, unless there are more than three of the other side before him. No player is allowed to loiter between the ball and the adversaries’ goal.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>In no case is holding a player, pushing with the hands, or tripping up allowed. Any player may prevent another from getting to the ball by any means consistent with the above rules.</span></li><li style="margin-left:17.6pt; padding-left:7.6pt;"><span>Every match shall be decided by a majority of goals.</span></li></ol></p>",
    "Bibliografia": "",
    "Crediti": "<p style='font-size:18px;'><b>Crediti</b><br><b>Images:</b>Mary Wardle<br><b>Transcription:</b>Mary Wardle </p>",
    "Autore": "<p align='right'><i>Mary Wardle </i></p>",
    "Mappa": "Immagini/Mappa/mappa12.png",
    "File": "Immagini/Proverbi/12.png",
    "Type": "true",
    "id": 12 }, 
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Per un punto Martin perse la cappa",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>A volte si va in rovina per una cosa di nulla. Gli spropositi sono come le spese, tutti si guardano dalle grandi, nessuno dalle piccole; e le piccole spese son quelle che minano la borsa. Il proverbio è nato da questo, così almeno si racconta a veglia.<br>Un tal Martino aveva un benefizio di cappa (titolo di benefizio secolare) coll’obbligo d’alloggiare tutti i pellegrini e passeggieri che capitassero per quelle parti. Sulla porta di casa si leggeva questo verso leonino:<BR><br><MI>Porta patens esto, nullo claudatur honesto</MI><BR><BR>Ora saltandogli addosso l’avarizia, cancellò il punto che era dopo la parola <MI>esto</MI>, e lo piantò dopo <MI>nullo</MI>, di modo che il verso, invece di dire come voleva l’obbligo del benefizio «Porta stai aperta; nessuna onesta persona rimanga esclusa», per quel punto levato di posto veniva a dire «Porta non t’aprire a nessuno: fuori anco i galantuomini». Accorti della ragia gli levarono il benefizio.</p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/5.png",
    "Type": "true",
    "id": 13
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/5.png",
    "Type": "false",
    "id": 14
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/5.png",
    "Type": "false",
    "id": 15
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Frate sfratato e cavol riscaldato, non fu mai buono",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Gli apostati son disprezzati da tutti. Gli abborre il partito che hanno abbandonato, non se ne fida il partito contrario. Quelli poi che vanno e vengono, che si girano a ogni vento come le banderuole «mutando parte dalla state al verno,» sono la feccia più spregevole che scoli dal letamajo de’ birboni. Son tanti gli esempi, per nostra disgrazia, che non so da che parte rifarmi. O Carbonari, o Liberali del ’31, ditelo voi! <BR>Si dice che l’amore una volta freddato è difficile che torni sincero e fervente come prima: difatti quando si tratta di rimpaciarsi, eccoti subito in campo il cavolo riscaldato. A volte però una grossezza insegna a tenere più di conto e dell’amante e dell’amico <br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/6.png",
    "Type": "true",
    "id": 16
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/6.png",
    "Type": "false",
    "id": 17
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/6.png",
    "Type": "false",
    "id": 18
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Chi altri giudica, sé condanna",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Perché l’uomo di rado, ma di rado bene, può fare a meno di misurare gli altri da sé medesimo. In questa gran commedia, per quanto si tenti di barattarci la parte uno coll’altro, siamo sempre noi che si recita. Quando nel Machiavelli e nel Guicciardini si trova tutto attribuito al tornaconto, nulla alla virtù, se ne tira la conseguenza che essi pure, figli dei tempi loro, non conoscessero altra norma che quella dell’utile. Del Guicciardini ognuno sa di che panni vestisse e come rimase col corto da piede, beffato da un fanciullo: riguardo al Machiavello pende la bilancia del dubbio, ma vi sono delle lettere che lo danno a conoscere per un furbo di tre cotte, e i furbi non sono tutti oro. Con tutto questo è una solenne arroganza voler giudicare di questa razza d’uomini con un cuoriciattolo avvezzo a palpitare sotto un panciotto di seta. Chi dispera dell’uomo, è segno che non sente di poter fidare in sé; ed è grande indizio di bontà, creder buoni gli altri. Per questo i migliori vanno per lo più a capo rotto, perché non conoscendo le vie coperte e tortuose del furbo e del briccone, non sospettano che vi sia altra strada fuori della maestra. Si batta questa via, ma si conoscano le scorciatoie<br>Quanti filosofi per aver voluto insegnare a camminare al mondo si sono scoperti zoppi! Quanti giornalisti censurando a traverso, pubblicano la propria imbecillità! Ma ognuno crede largo il cerchio dell’idee quanto glielo disegnano le seste di casa, e vorrebbe le teste degli uomini accomodate al giro del suo cappello.<BR></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/7.png",
    "Type": "true",
    "id": 19
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/7.png",
    "Type": "false",
    "id": 20
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/7.png",
    "Type": "false",
    "id": 21
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Chi va piano, va sano",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p><MI>Tarde sed tute</MI>, dicevano i Latini. Questa sentenza è simboleggiata in una Tartaruga, come fra gli altri luoghi si può vedere nelle porte del Duomo di Pisa. L’animale, per dire il vero, è un po’ troppo flemmatico, e c’è da addormentarcisi su: la sua è, andare d’un passo naturale, senza scalmanarsi, ma che ci si veda uno che ha voglia d’arrivare. Andatelo a dire a certi tali! Vi spiattellano una Storia Universale, come il cieco le sue. Purché s’afferrino le cose del momento, al poi ci pensi chi vuole: ecco l’origine di tanti naufragi e politici e letterari. Presto e male, è l’epigrafe del tempo.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/8.png",
    "Type": "true",
    "id": 22
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/8.png",
    "Type": "false",
    "id": 23
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/8.png",
    "Type": "false",
    "id": 24
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Chi biasima vuol comprare",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Oramai è tanta la malafede e la diffidenza nelle compre e vendita, che prima di venire all’accordo bisogna fare una storia lunga, nojosa, vergognosissima. Di qua e di là si giura per Cristo e per i Santi, si palleggia la parola d’onore e la coscienza, e si finisce per rinnegare tutte queste belle cose per un soldo. Certe chieste a volte fanno montare i rossori sul viso: e si sceglie di troncare la contrattazione o di lasciarsi mettere in mezzo piuttosto che raddoppiarsi la vergogna d’offrire la metà.<br>Benedetti i fornai! Di fatto, d’una cosa che ha un prezzo fisso si suol dire: è come andare a comprare un pane al fornajo<BR>Per certe pantomime è famosa la gente del contado. Fanno vista d’avere scambiato bottega, e poi: — Oh! già che son qui, quant’ho a dare di questo? Altri vorranno un pajolo, e cominceranno da mettere a prezzo una lucernina. Che serve confondersi? Il mondo non è altro che chiacchiera e scena<BR>Le ragazze quando vedono che i giovanotti o tiran di lungo o le canzonano, dicono subito: <MI>sie sie, chi biasima, vuol comprare.</MI><BR></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/9.png",
    "Type": "true",
    "id": 25
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/9.png",
    "Type": "false",
    "id": 26
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/9.png",
    "Type": "false",
    "id": 27
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Una Rondine non fa primavera",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Vi sono taluni che per aver dato buon saggio di sé per una volta tanto, si tengono oramai certi e sicuri d’uno scampolino d’eternità. Male però a quell’albero che fiorisce una volta sola. Tempo fa, venne in ballo la Rondine a conto d’un tale, che per avere imbroccato un epigramma, ebbe la modestia di dire: il Pananti non è morto tutto. Se non è a proposito, non sarà inutile, aggiungere che il Pananti è uno di quelli che negli scritti hanno fatto più uso di proverbi e di modi di dire. Gli epigrammi, le prose volanti, gli scherzi, e il <MI>Poeta di Teatro</MI>, ne sono pieni zeppi, e gl’Italiani gli cercano come miniere di lingua viva e schiettissima. Era lepidissimo raccontatore da tenere a bada la brigata tutta una sera. Parlava pronto e brioso come scriveva; era semplice negli abiti e anco un po’ al di là come il babbo La Fontaine. Per le vie, per le botteghe, per le conversazioni stava a balzello di modi e di detti arguti; e beccatone uno che gli paresse il caso, via a farne un raccontino o un epigramma. Aveva patito di stizze letterarie, ma era stato provocato alla peggio, come è usato sempre fra la razza pettegola che<BR><BR> <MI>Il furor letterato a guerra mena</MI><BR><BR>Negli ultimi tempi patì di stizze politiche; era però un galantuomo, un uomo schietto e modesto. Il fatto lo provi. Viaggiando a piedi in Sicilia, sorpreso un giorno dalla pioggia, si rifugiò in casa d’un benestante di campagna, e fra gli altri libercoli d’uno scaffaletto, vide quello suo degli epigrammi. L’aprì e per prendersi gioco disse al suo ospite: - Come mai avete qui questo librucciaccio? -  L’ospite che non lo conosceva per l’autore, rispose subito: — Come librucciaccio! È un libro pieno di spirito, un libro divertentissimo. — Eh eh, riprese il Pananti: - Leggetelo meglio, e non direte così. — Leggetelo piuttosto voi, — gli disse l’altro: stettero a tu per tu tanto che questi gli ebbe a dire che quasi s’era pentito d’avergli dato ricovero. Direte: tirò in lungo la burla per annusare la lode a narici più libere, ma il bello è che partì senza darsi a conoscere, e si lasciò tenere o per uno stravagante o per un bue. Non è da tutti. Poco tempo avanti la sua morte, l’ingegno non lo serviva più, pronto e vivace come prima. Ammattì otto giorni, come diceva egli stesso, a conto d’una rima facilissima, né ci fu verso che gli venisse. Chi l’udì allora ne rimase stupito: quando poi dopo due o tre giorni lo seppe morto, ne intese il perché, e gliene crebbe il dolore.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/10.png",
    "Type": "true",
    "id": 28
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/10.png",
    "Type": "false",
    "id": 29
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/10.png",
    "Type": "false",
    "id": 30
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Il lume è una mezza compagnia",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>È vero specialmente per gli addolorati. La mente distratta dall’occhio (che se non avvisa del tutto, non può fare a meno di non sentire l’aspetto degli oggetti esterni), non ha l’agio di assidersi tutta nel suo dolore. Difatto chi si raccoglie per pensare, o chiude gli occhi o gli fissa al cielo o gli conficca in terra. L’ora più malinconica d’un giorno non lieto, è quella del tramonto. Bene l’hanno vista i poeti:<br><br>Era già l’ora che volge il desio<br>&nbsp;&nbsp;&nbsp;A’ naviganti, e intenerisce il core<br>&nbsp;&nbsp;&nbsp;Lo dì c’han detto a’ dolci amici addio;<br>E che lo nuovo peregrin, d’amore<br>&nbsp;&nbsp;&nbsp;Punge, se ode squilla di lontano<br>&nbsp;&nbsp;&nbsp;Che paja il giorno pianger che si muore.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<mi>Purgatorio</mi><br><br>A volte lo spengersi del lume pare che ti tolga il respiro, come perdere di vista una cara persona. La luce stessa dell’alba non conforta lo studioso della lucerna che gli s’è spenta sul libro, perché allora solamente avverte la fatica durata e il volo rapido e tranquillo dell’ore tolte al riposo.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/11.png",
    "Type": "true",
    "id": 31
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/11.png",
    "Type": "false",
    "id": 32
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/11.png",
    "Type": "false",
    "id": 33
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "La lontananza ogni gran piaga sana<BR>Lontan dagli occhi, lontan dal core",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Questi due proverbi quanto debbono essere amari al cuore degli esuli! La terra nativa e le persone che ci hanno veduto nascere e quelle che sono cresciute con noi, non escono mai dalla mente né per lasso di tempo né per distanza di luogo. La nostra mente, anzi la vita medesima, si forma, si nutre, e finalmente non vive che delle abitudini delle memorie della prima età: di quell’età nella quale essa, come cera ben disposta, riceve e ritiene per sempre l’impronta che vi si sigilla. Per questo l’uomo, sbalzato a vivere fuori del suo paese, è come un albero svelto che lascia nel terreno molta parte delle sue radici. Anzi il dolore s’avviva in quella smania malinconica che c’invade l’animo quando c’è impedito di dare libero il volo ai nostri desideri. Il pensiero, come la rondine, torna sempre al suo nido, e chi può darsi pace dell’esilio o del vivere lontani da una cara persona, non ha mai amato, né mai sentito d’avere una patria. In quel libretto delle <mi>Osservazioni semiserie sull’Inghilterra</mi>, Pecchio avrebbe potuto fare a meno di rubare le fomente di Sancio Panza per bagnarsene la ferita dell’esilio. A un Italiano, a un figlio strappato dalle braccia di questa nostra madre comune, per non essersi mostrato bastardo, non istà bene scherzare su certe corde.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/12.png",
    "Type": "true",
    "id": 34
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/12.png",
    "Type": "false",
    "id": 35
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/12.png",
    "Type": "false",
    "id": 36
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Chi comincia male, finisce peggio",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Non è sempre vero: a volte un errore ti rimanda in istrada e fa sì che tu non n’esca mai più. <MI>Gli errori sono i nostri maestri</MI>, dice un altro proverbio; e ve n’è uno ancora che dice: <MI>È meglio pentirsi che non avere sbagliato mai</MI>. Chi non ha mai errato è sempre sul punto di trovarsi avviluppato in uno sproposito, perché l’occasione lo coglie alla sprovvista, mentre chi ha fatti degli sbagli va avvisato in mezzo ai pericoli. L’uomo per quanto sia di buona pasta, cerchi di migliorare se stesso coll’esperienza e del bene e del male; e beato quello che ha l’abitudine di chiamare i pensieri a raccolta e il coraggio ora di compiacersi, ora di vergognarsi di sé medesimo. Perché la compiacenza del bene operato, ti conferma negli abiti buoni, e t’allontana dal male la vergogna d’esservi caduto talvolta. Non si può dire che abbiano vissuto mai quelli che non hanno mai sentito brontolarsi dentro ora la lode ora la rampogna della coscienza. L’amor proprio è il nostro nemico occulto, che a forza di moine ci liscia, ci gonfia e ci tura gli occhi e gli orecchi: chi è arrivato a schiacciarlo e a darsi dell’asino e anco del birbone di tutto cuore, non è pezza ordinaria. Quelli che non sanno piegare la testa dura e superba a umiliarsi neppure nel segreto del loro cuore, sono i soli che comincino male e finiscano peggio. Non parliamo degl’insensati, di quelli che non hanno tutti i loro giorni, perché costoro vivono alla cieca e come suol dirsi, fanno alla mora in sepoltura. Non è raro vedere sia uomo sia donna che deluso nel suo primo amore, prima di lasciare passare la febbre e d’uscir di convalescenza, o per distrarsi, o peggio per far dispetto a chi l’ha burlato, si rifugia in un matrimonio fatto a occhi e croce. Eccovi un disperato che ha cominciato male e finito peggio.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/13.png",
    "Type": "true",
    "id": 37
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/13.png",
    "Type": "false",
    "id": 38
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/13.png",
    "Type": "false",
    "id": 39
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Chi tosto s’adira, tosto si placa",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>A volte questa subitaneità può essere indizio di leggerezza: non è cosa rara il riscontrarla negli animi schietti e amorevoli. Direi però di stare in guardia contro questo difetto, perché lasciandolo trascorrere ti fa noioso e ridicolo. Il Monti era irascibilissimo e placabilissimo, e perciò nel tempo che egli signoreggiava sugli scrittori del suo tempo, non vi fu sciolo che con un po’ d’astuzia non sapesse farne alla palla.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/14.png",
    "Type": "true",
    "id": 40
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/14.png",
    "Type": "false",
    "id": 41
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Proverbi/14.png",
    "Type": "false",
    "id": 42
  },
  {
    "Sottotitolo": "Proverbio",
    "Titolo": "Il riso fa buon sangue",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "<p>Vuol dire che l’allegria conferisce alla salute. Ecco perché disse Sterne nel <MI>Viaggio sentimentale</MI> che un sorriso aggiunge un filo alla trama della vita; alla quale sentenza consuona l’altro proverbio <MI>Chi ride, leva un chiodo alla bara</MI>. Anche Béranger dice in una delle sue Canzoni, che l’allegria ci fa buoni; e i Francesi hanno diritto di dir ciò, perché, a prenderli in blocco, sono la migliore e la più lieta gente del mondo. E l’allegria non solamente li fa buoni, ma li fa anche valorosi; e difatto non v’è nazione che vada incontro alla morte celiando e cantando come ci va la Francese. Alle cose più serie e più terribili mescolano naturalmente lo scherzo ed io non sono del parere di coloro che attribuiscono ciò unicamente a una tal quale leggerezza dell’indole loro. Il giorno dopo che fu presa la Bastiglia, su la piazza dov’era stata quella prigione di Stato, fu veduto un palo con il cartello: <MI>qui si balla</MI>. I cannoni degli Austriaci, dei Prussiani e dei Russi sono stati presi al canto della Marsigliese. Il cuore dei fanciulli e dei giovanetti è buono perché è lieto e la stessa malinconia è dolce perché sorride.<br></p>",
    "Firma": "Giuseppe Giusti",
    "File": "Immagini/Proverbi/spiegati/15.png",
    "Type": "true",
    "id": 43
  },
      {
    "Sottotitolo": "Voci",
    "Titolo": "",
     "Image": "Immagini/tracce/traccia_1.png",
    "Descrizione": "",
    "Firma": "",
    "File": "Immagini/Voci/15.png",
    "Type": "false",
    "id": 44
  }
]
  